
const maps = [
    {
        location: 'MAPPA 0',
        description: 'Inizio',
        position: [0, 0],
        image: 'img/maps/start-woods.jpg',
        log: '> You feel dizzy is this the starting point?',
        btnDisableUp: false,
        btnDisableDw: true,
        btnDisableDx: false,
        btnDisableSx: false,
        btnDisableFight: true,
        btnDisableFight: true,
        btnDisableRun: true,
        btnDisablePray: true,
        btnDisableRoll: false,
        btnDisableSearch: false
    },
    {
        location: 'MAPPA 1',
        description: 'Forest',
        position: [1, 0],
        image: 'img/maps/map_01_00.jpg',
        log: '>',
        btnDisableUp: true,
        btnDisableDw: false,
        btnDisableDx: false,
        btnDisableSx: true,
        btnDisableFight: true,
        btnDisableRun: true,
        btnDisablePray: true,
        btnDisableRoll: true,
        btnDisableSearch: false
    },
    {
        location: 'MAPPA 2',
        description: 'Forest',
        position: [1, 1],
        image: 'img/maps/map_01_01.jpg',
        log: '>',
        btnDisableUp: true,
        btnDisableDw: false,
        btnDisableDx: false,
        btnDisableSx: false,
        btnDisableFight: true,
        btnDisableRun: true,
        btnDisablePray: true,
        btnDisableRoll: true,
        btnDisableSearch: false
    },
    {
        location: 'MAPPA 3',
        description: 'Forest',
        position: [0, 1],
        image: 'img/maps/map_00_01.jpg',
        log: '>',
        btnDisableUp: false,
        btnDisableDw: false,
        btnDisableDx: false,
        btnDisableSx: false,
        btnDisableFight: true,
        btnDisableRun: true,
        btnDisablePray: true,
        btnDisableRoll: true,
        btnDisableSearch: false
    },
    {
        location: 'MAPPA 4',
        description: 'Well',
        position: [-1, 1],
        image: 'img/maps/well_-01_01.jpg',
        log: '>',
        btnDisableUp: false,
        btnDisableDw: false,
        btnDisableDx: false,
        btnDisableSx: true,
        btnDisableFight: true,
        btnDisableRun: true,
        btnDisableRest: false,
        btnDisablePray: true,
        btnDisableRoll: true,
        btnDisableSearch: false
    },
    {
        location: 'MAPPA 5',
        description: 'forest',
        position: [-1, 2],
        image: 'img/maps/map_-01_02.jpg',
        log: '>',
        btnDisableUp: false,
        btnDisableDw: true,
        btnDisableDx: true,
        btnDisableSx: false,
        btnDisableFight: true,
        btnDisableRun: true,
        btnDisableRest: false,
        btnDisablePray: true,
        btnDisableRoll: true,
        btnDisableSearch: false
    },
    {
        location: 'MAPPA 6',
        description: 'Forest',
        position: [0, 2],
        image: 'img/maps/beggar_00_02.jpg',
        log: '>',
        btnDisableUp: false,
        btnDisableDw: true,
        btnDisableDx: true,
        btnDisableSx: false,
        btnDisableFight: true,
        btnDisableRun: true,
        btnDisableRest: false,
        btnDisablePray: true,
        btnDisableRoll: true,
        btnDisableSearch: false
    },
    {
        location: 'MAPPA 7',
        description: 'Forest',
        position: [1, 2],
        image: 'img/maps/beggar_01_02.jpg',
        log: '>',
        btnDisableUp: false,
        btnDisableDw: true,
        btnDisableDx: true,
        btnDisableSx: false,
        btnDisableFight: true,
        btnDisableRun: true,
        btnDisableRest: false,
        btnDisablePray: true,
        btnDisableRoll: true,
        btnDisableSearch: false
    },
    {
        location: 'MAPPA 8',
        description: 'Home',
        position: [0, -1],
        image: 'img/maps/map_00_-01.jpg',
        log: '>',
        btnDisableUp: true,
        btnDisableDw: true,
        btnDisableDx: false,
        btnDisableSx: false,
        btnDisableFight: true,
        btnDisableRun: true,
        btnDisableRest: false,
        btnDisablePray: true,
        btnDisableRoll: true,
        btnDisableSearch: false
    },
    {
        location: 'MAPPA 9',
        description: 'Symbol',
        position: [2, 2],
        image: 'img/maps/map_02_02.jpg',
        log: '>',
        btnDisableUp: true,
        btnDisableDw: false,
        btnDisableDx: false,
        btnDisableSx: true,
        btnDisableFight: true,
        btnDisableRun: true,
        btnDisableRest: false,
        btnDisablePray: true,
        btnDisableRoll: true,
        btnDisableSearch: false
    },
    {
        location: 'MAPPA 10',
        description: 'Door',
        position: [0, -2],
        image: 'img/maps/map_00_-02.jpg',
        log: '>',
        btnDisableUp: true,
        btnDisableDw: false,
        btnDisableDx: false,
        btnDisableSx: true,
        btnDisableFight: true,
        btnDisableRun: true,
        btnDisableRest: false,
        btnDisablePray: true,
        btnDisableRoll: true,
        btnDisableSearch: false
    },
    {
        location: 'MAPPA 11',
        description: 'Portal',
        position: [2, 3],
        image: 'img/maps/map_02_03.jpg',
        log: '>',
        btnDisableUp: true,
        btnDisableDw: true,
        btnDisableDx: true,
        btnDisableSx: false,
        btnDisableFight: true,
        btnDisableRun: true,
        btnDisableRest: false,
        btnDisablePray: true,
        btnDisableRoll: true,
        btnDisableSearch: false
    },
    {
        location: 'MAPPA 12',
        description: 'Home inside',
        position: [-1, -2],
        image: 'img/maps/map_-01_-02.jpg',
        log: '>',
        btnDisableUp: false,
        btnDisableDw: true,
        btnDisableDx: true,
        btnDisableSx: true,
        btnDisableFight: true,
        btnDisableRun: true,
        btnDisableRest: false,
        btnDisablePray: true,
        btnDisableRoll: true,
        btnDisableSearch: false
    },
    {
        location: 'INCUBO',
        description: 'Wake up',
        position: [10, 10],
        image: 'img/mobs/mob00-00.jpg',
        log: '>',
        btnDisableUp: true,
        btnDisableDw: true,
        btnDisableDx: true,
        btnDisableSx: true,
        btnDisableFight: false,
        btnDisableRun: false,
        btnDisableRest: true,
        btnDisablePray: false,
        btnDisableRoll: true,
        btnDisableSearch: true
    }
]

