// ARRAY MAPS
const maps = [
    {
        location: 'MAPPA 0',
        description: 'These rays of light that penetrate the darkness are a blessing. However there something hidden in this abnormal quietness. Where am I?',
        position: [0, 0],
        image: 'img/maps/start-woods.jpg',
        log: '>',
        btnDisableUp: false,
        btnDisableDw: true,
        btnDisableDx: false,
        btnDisableSx: false,
        btnDisableFight: true,
        btnDisableRun: true,
        btnDisablePray: true,
        btnDisableRoll: true,
        btnDisableSearch: false,
        btnDisableBook: true,
        btnDisableGuide: false,
        btnDisableEye: true,
        btnDisableArmor: true,
        btnDisableWeapon: true
    },
    {
        location: 'MAPPA 1',
        description: 'Trees trees and more trees. A beam of light comes through the bare branches. Powerless in this never ending forest.',
        position: [1, 0],
        image: 'img/maps/map_01_00.jpg',
        log: '>',
        btnDisableUp: true,
        btnDisableDw: false,
        btnDisableDx: false,
        btnDisableSx: true,
        btnDisableFight: true,
        btnDisableRun: true,
        btnDisablePray: true,
        btnDisableRoll: true,
        btnDisableSearch: false,
        btnDisableBook: true,
        btnDisableGuide: false,
        btnDisableEye: true,
        btnDisableArmor: true,
        btnDisableWeapon: true
    },
    {
        location: 'MAPPA 2',
        description: 'It seems that this thick blanket covering the path and the surge of light is a living thing, blinding every living creature',
        position: [1, 1],
        image: 'img/maps/map_01_01.jpg',
        log: '>',
        btnDisableUp: true,
        btnDisableDw: false,
        btnDisableDx: false,
        btnDisableSx: false,
        btnDisableFight: true,
        btnDisableRun: true,
        btnDisablePray: true,
        btnDisableRoll: true,
        btnDisableSearch: false,
        btnDisableBook: true,
        btnDisableGuide: false,
        btnDisableEye: true,
        btnDisableArmor: true,
        btnDisableWeapon: true
    },
    {
        location: 'MAPPA 3',
        description: 'You think there is a lonely woman lost and desperate in the midst of nowhere, or is it just You...',
        position: [0, 1],
        image: 'img/maps/map_00_01.jpg',
        log: '>',
        btnDisableUp: false,
        btnDisableDw: false,
        btnDisableDx: false,
        btnDisableSx: false,
        btnDisableFight: true,
        btnDisableRun: true,
        btnDisablePray: true,
        btnDisableRoll: true,
        btnDisableSearch: false,
        btnDisableBook: true,
        btnDisableGuide: false,
        btnDisableEye: true,
        btnDisableArmor: true,
        btnDisableWeapon: true
    },
    {
        location: 'MAPPA 4',
        description: 'Not long since there was a time that the well was in full use and need. The tiny bird is hopeful and patient.',
        position: [-1, 1],
        image: 'img/maps/well_-01_01.jpg',
        log: '>',
        btnDisableUp: false,
        btnDisableDw: true,
        btnDisableDx: false,
        btnDisableSx: true,
        btnDisableFight: true,
        btnDisableRun: true,
        btnDisableRest: false,
        btnDisablePray: true,
        btnDisableRoll: true,
        btnDisableSearch: false,
        btnDisableBook: true,
        btnDisableGuide: false,
        btnDisableEye: true,
        btnDisableArmor: true,
        btnDisableWeapon: true
    },
    {
        location: 'MAPPA 5',
        description: 'The dead leaves cover the lifeless path. Every step makes the ground scream aloud your presence. You feel uncomfortable in the poor light  that filters timidly.',
        position: [-1, 2],
        image: 'img/maps/map_-01_02.jpg',
        log: '>',
        btnDisableUp: false,
        btnDisableDw: true,
        btnDisableDx: true,
        btnDisableSx: false,
        btnDisableFight: true,
        btnDisableRun: true,
        btnDisableRest: false,
        btnDisablePray: true,
        btnDisableRoll: true,
        btnDisableSearch: false,
        btnDisableBook: true,
        btnDisableGuide: false,
        btnDisableEye: true,
        btnDisableArmor: true,
        btnDisableWeapon: true
    },
    {
        location: 'MAPPA 6',
        description: 'In the distance a misty fog had enveloped the area. The shape of a person appeared running towards North. The animals strangely were silent.',
        position: [0, 2],
        image: 'img/maps/beggar_00_02.jpg',
        log: '>',
        btnDisableUp: false,
        btnDisableDw: true,
        btnDisableDx: true,
        btnDisableSx: false,
        btnDisableFight: true,
        btnDisableRun: true,
        btnDisableRest: false,
        btnDisablePray: true,
        btnDisableRoll: true,
        btnDisableSearch: false,
        btnDisableBook: true,
        btnDisableGuide: false,
        btnDisableEye: true,
        btnDisableArmor: true,
        btnDisableWeapon: true
    },
    {
        location: 'MAPPA 7',
        description: 'The feeling was ominous. Rays of light filtered through the trees. The branches yielded to the slight breeze.',
        position: [1, 2],
        image: 'img/maps/beggar_01_02.jpg',
        log: '>',
        btnDisableUp: false,
        btnDisableDw: true,
        btnDisableDx: true,
        btnDisableSx: false,
        btnDisableFight: true,
        btnDisableRun: true,
        btnDisableRest: false,
        btnDisablePray: true,
        btnDisableRoll: true,
        btnDisableSearch: false,
        btnDisableBook: true,
        btnDisableGuide: false,
        btnDisableEye: true,
        btnDisableArmor: true,
        btnDisableWeapon: true
    },
    {
        location: 'MAPPA 8',
        description: 'A homely cottage with some signs of life. No smoke appears from the chimney. Even though the damp and cold would necessitate some warmth. A weird feeling. Was this a noose?',
        position: [0, -1],
        image: 'img/maps/map_00_-01.jpg',
        log: '>',
        btnDisableUp: true,
        btnDisableDw: true,
        btnDisableDx: false,
        btnDisableSx: false,
        btnDisableFight: true,
        btnDisableRun: true,
        btnDisableRest: false,
        btnDisablePray: true,
        btnDisableRoll: true,
        btnDisableSearch: false,
        btnDisableBook: true,
        btnDisableGuide: false,
        btnDisableEye: true,
        btnDisableArmor: true,
        btnDisableWeapon: true
    },
    {
        location: 'MAPPA 9',
        description: 'Sticks that seem to have been tied in an haphazard method in actual fact have an ominous and mystical explanation. Who and why ??',
        position: [2, 2],
        image: 'img/maps/map_02_02.jpg',
        log: '>',
        btnDisableUp: true,
        btnDisableDw: false,
        btnDisableDx: false,
        btnDisableSx: true,
        btnDisableFight: true,
        btnDisableRun: true,
        btnDisableRest: false,
        btnDisablePray: true,
        btnDisableRoll: true,
        btnDisableSearch: false,
        btnDisableBook: true,
        btnDisableGuide: false,
        btnDisableEye: true,
        btnDisableArmor: true,
        btnDisableWeapon: true
    },
    {
        location: 'MAPPA 10',
        description: 'An old abandoned wooden door. Unkempt and deserted. The iron knocker in disuse and no longer heard. ',
        position: [0, -2],
        image: 'img/maps/map_00_-02.jpg',
        log: '>',
        btnDisableUp: true,
        btnDisableDw: false,
        btnDisableDx: false,
        btnDisableSx: true,
        btnDisableFight: true,
        btnDisableRun: true,
        btnDisableRest: false,
        btnDisablePray: true,
        btnDisableRoll: true,
        btnDisableSearch: false,
        btnDisableBook: true,
        btnDisableGuide: false,
        btnDisableEye: true,
        btnDisableArmor: true,
        btnDisableWeapon: true
    },
    {
        location: 'MAPPA 11',
        description: 'In the midst of this forest unexpected life comes to being. A round emerald green vibrant ball sizzles and rotates. A figure hunched motionless.',
        position: [2, 3],
        image: 'img/maps/map_02_03.jpg',
        log: '>',
        btnDisableUp: true,
        btnDisableDw: true,
        btnDisableDx: true,
        btnDisableSx: false,
        btnDisableFight: true,
        btnDisableRun: true,
        btnDisableRest: false,
        btnDisablePray: true,
        btnDisableRoll: true,
        btnDisableSearch: false,
        btnDisableBook: true,
        btnDisableGuide: false,
        btnDisableEye: true,
        btnDisableArmor: true,
        btnDisableWeapon: true
    },
    {
        location: 'MAPPA 12',
        description: 'The lady in white looks anxious, distrought and helpless. A single cosy wrought iron bed. A portait of a white cat stands proudly on the mantelpiece The bedside light adequate. The windows dressed with laced curtains allow some natural light flow.',
        position: [-1, -2],
        image: 'img/maps/map_-01_-02.jpg',
        log: '>',
        btnDisableUp: false,
        btnDisableDw: true,
        btnDisableDx: true,
        btnDisableSx: true,
        btnDisableFight: true,
        btnDisableRun: true,
        btnDisableRest: false,
        btnDisablePray: true,
        btnDisableRoll: true,
        btnDisableSearch: false,
        btnDisableBook: true,
        btnDisableGuide: false,
        btnDisableEye: true,
        btnDisableArmor: true,
        btnDisableWeapon: true
    },
    {
        location: 'MAPPA 13',
        description: 'You pass the portal. Another nightmare begins: Time to go to work...',
        position: [1, 3],
        image: 'img/events/wakeup.jpg',
        log: '>',
        btnDisableUp: true,
        btnDisableDw: true,
        btnDisableDx: true,
        btnDisableSx: true,
        btnDisableFight: true,
        btnDisableRun: true,
        btnDisableRest: true,
        btnDisablePray: true,
        btnDisableRoll: true,
        btnDisableSearch: true,
        btnDisableBook: true,
        btnDisableGuide: false,
        btnDisableEye: true,
        btnDisableArmor: true,
        btnDisableWeapon: true
    },
    {
        location: 'INCUBO',
        description: 'Wake up',
        position: [10, 10],
        image: 'img/events/incubo.jpg',
        log: '>',
        btnDisableUp: true,
        btnDisableDw: true,
        btnDisableDx: true,
        btnDisableSx: true,
        btnDisableFight: false,
        btnDisableRun: false,
        btnDisableRest: true,
        btnDisablePray: false,
        btnDisableRoll: true,
        btnDisableSearch: true,
        btnDisableBook: true,
        btnDisableGuide: false,
        btnDisableEye: true,
        btnDisableArmor: true,
        btnDisableWeapon: true
    },
]

